# Generated by Django 6.0.4 on 2026-04-22 10:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pension_api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_deceased',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='Nominee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nominee_pension_id', models.CharField(db_index=True, max_length=255, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('relation', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='nominees', to='pension_api.user')),
            ],
        ),
        migrations.CreateModel(
            name='NomineeFaceEncoding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('embedding', models.JSONField()),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='face_encodings', to='pension_api.nominee')),
            ],
        ),
        migrations.CreateModel(
            name='NomineeVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('nominee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='pension_api.nominee')),
            ],
        ),
    ]
